version: '3.5'

services:
  postgres:
    container_name: postgres-tcc
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2405
      POSTGRES_DB: tcc-project
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"